# BasketBuddy Privacy Policy

_Last updated: 2026-04-11_

This is seed text for the BasketBuddy v2 privacy policy. Publish it at a
stable URL (e.g. `https://basketbuddy.app/privacy`) and point the
`EXPO_PUBLIC_PRIVACY_POLICY_URL` build-time variable at that URL so the
"Privacy Policy" row inside Settings opens the published copy.

## 1. Who we are

BasketBuddy is a local-only shopping list and price tracker for iOS and
Android. The app is published by the developer whose contact details are
available on the app store listing.

## 2. What we store

All shopping lists, templates, price history, and app settings are stored
**on your device only**. BasketBuddy does not run a backend and does not
upload your data to a cloud service.

## 3. Advertising (Google AdMob)

The free version of the app shows banner ads served by Google AdMob. To
serve ads, Google may collect:

- Your device's advertising identifier (IDFA on iOS, AAID on Android).
- Coarse location (country-level, derived from IP address).
- App version and device type.
- Ad interaction events (impressions, clicks).

If you are in the European Economic Area, the United Kingdom, or
Switzerland, BasketBuddy uses Google's User Messaging Platform (UMP) to
request your consent before any personalized ads are loaded.

On iOS, BasketBuddy asks you for App Tracking Transparency permission. If
you decline, ads will continue to show but will not be personalized.

You can read Google's privacy policy at
<https://policies.google.com/privacy>.

## 4. In-app purchases (RevenueCat)

When you purchase "Remove Ads Forever", the transaction is handled by
Apple (iOS) or Google (Android) and validated by RevenueCat. RevenueCat
receives a random anonymous user identifier generated by BasketBuddy
(not linked to your email, name, or phone number), together with the
purchase receipt. This is used only to verify and restore your purchase
across devices.

You can read RevenueCat's privacy policy at
<https://www.revenuecat.com/privacy>.

## 5. Crash reporting (Sentry)

BasketBuddy reports uncaught errors to Sentry to help diagnose bugs.
Crash reports include the error message, a stack trace, the app version,
and the device model — but **never** the contents of your shopping lists
or price history.

You can read Sentry's privacy policy at
<https://sentry.io/privacy/>.

## 6. Your rights

Because BasketBuddy stores your shopping data locally, deleting the app
erases it permanently. Use "Export CSV" in Settings before uninstalling
if you want to keep a copy.

To opt out of ad personalization:

- **iOS**: Settings → Privacy & Security → Tracking → toggle off for BasketBuddy.
- **Android**: Settings → Google → Ads → "Delete advertising ID".
- **EU/UK/CH**: Re-open the consent form via Settings → Privacy Policy (v2.1+).

## 7. Changes to this policy

If this policy materially changes, BasketBuddy will surface a one-time
notice on next launch and update the `Last updated` date above.

## 8. Contact

Questions? Contact the developer using the email address on the app
store listing.
